@startuml
(*) --> "接入应用请求身份认证"
if "验证应用是否合法" then
 --> [合法] "使用微信网页授权\n获取当前用户OpenID"
 if "当前用户是否已绑定" then
 --> [已绑定] "读取绑定的CAS信息"
 --> "向应用提供微信OpenID和CAS认证信息"
 else
 --> [未绑定] "发起CAS认证流程"
 --> "绑定用户微信OpenID和CAS认证信息"
 --> "向应用提供微信OpenID和CAS认证信息"
 endif
 --> (*)
else
 --> [不合法] 报错
 --> (*)
endif
 
@enduml